name: Publish Docker images
on:
  push:
    branches:
      - main

jobs:

  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v4.2.1
        with:
          push: true
          context: .
          file: docker/image2model/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cmahnke/oss-exhibition-tools/image2model:latest
